# The name of the relative directory where the
# following files are located.
dirname=dat

# User data files.
filename_home=home.ras
filename_school=school.ras
filename_other=other.ras
filename_username=username.txt